apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: copilot-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/auth-url: "https://{{ .Values.authDomain }}/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://{{ .Values.authDomain }}/oauth2/start?rd=$scheme://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization, X-Auth-Request-User, X-Auth-Request-Email"
    nginx.ingress.kubernetes.io/affinity: "cookie"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - "{{ .Values.host }}"
    secretName: "{{ .Values.tls.secretName }}"
  rules:
  - host: "{{ .Values.host }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: copilot
            port:
              number: 8000
